# Generated by Django 4.2.11 on 2025-03-29 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental", "Rental Payment"),
                            ("deposit", "Security Deposit"),
                            ("late_fee", "Late Fee"),
                            ("damage_fee", "Damage Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("stripe", "Credit Card (Stripe)"),
                            ("venmo", "Venmo"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("receipt_sent", models.BooleanField(default=False)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("refund_date", models.DateTimeField(blank=True, null=True)),
                (
                    "refund_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="rentals.rental",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="VenmoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venmo_transaction_id", models.CharField(max_length=255)),
                (
                    "venmo_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "venmo_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "venmo_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venmo_transaction",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_charge_id", models.CharField(max_length=255)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("card_brand", models.CharField(blank=True, max_length=50, null=True)),
                ("billing_address", models.TextField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_transaction",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayPalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paypal_order_id", models.CharField(max_length=255)),
                (
                    "paypal_payer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paypal_payer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("payment_completed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_transaction",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental", "Rental Payment"),
                            ("deposit", "Security Deposit"),
                            ("late_fee", "Late Fee"),
                            ("damage_fee", "Damage Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("stripe", "Credit Card (Stripe)"),
                            ("venmo", "Venmo"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("receipt_sent", models.BooleanField(default=False)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("refund_date", models.DateTimeField(blank=True, null=True)),
                (
                    "refund_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rentals.rental",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment",
                "verbose_name_plural": "historical payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
