# Generated by Django 4.2.11 on 2025-04-02 05:05

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_default_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=users.fields.FlexiblePhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
