# Generated by Django 4.2.11 on 2025-04-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_phone_number"),
        ("users", "0003_create_default_site"),
    ]

    operations = []
