# Generated by Django 4.2.11 on 2025-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
