# Generated by Django 4.2.11 on 2025-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_searchlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="Indicates if the maintenance is completed"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="scheduled_date",
            field=models.DateField(
                blank=True, help_text="Date when maintenance is scheduled", null=True
            ),
        ),
    ]
