# Generated by Django 4.2.11 on 2025-03-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_add_manual_fields"),
        ("inventory", "0003_maintenancerecord_is_completed_and_more"),
    ]

    operations = []
