# Generated by Django 4.2.11 on 2025-04-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_merge_20250331_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalequipment",
            name="manual_file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="manual_last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="manual_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
