# Generated by Django 4.2.11 on 2025-04-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
