# Generated by Django 4.2.11 on 2025-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_equipment_quantity_historicalequipment_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="replacement_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="replacement_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
