name: Deploy to GCP with Cloud Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: 'Google Auth'
      id: 'auth' 
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        create_credentials_file: true
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Fix GCloud Config
      run: |
        gcloud auth activate-service-account --key-file=${{steps.auth.outputs.credentials_file_path}}
        gcloud config set account terraformer@${{ vars.GOOGLE_PROJECT }}.iam.gserviceaccount.com
        gcloud config set project ${{ vars.GOOGLE_PROJECT }}

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config=cloudbuild.yaml
