name: Deploy to GCP with Cloud Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: 'Google Auth'
      id: 'auth' 
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        create_credentials_file: true
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: happypathway-1522441039906
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1

    - name: Get Terraform Output
      id: tf-output
      working-directory: ./backend-state
      run: |
        terraform init
        echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT
        echo "logging_bucket_name=$(terraform output -raw logging_bucket_name)" >> $GITHUB_OUTPUT

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit \
          --config=cloudbuild.yaml \
          --gcs-source-staging-dir=gs://${{ steps.tf-output.outputs.bucket_name }}/tmp \
          --gcs-log-dir=gs://${{ steps.tf-output.outputs.logging_bucket_name }}/logs \
          --service-account=terraformer@happypathway-1522441039906.iam.gserviceaccount.com
    