name: Deploy to GCP with Cloud Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: 'Google Auth'
      id: 'auth' 
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        create_credentials_file: true
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: Get Terraform Output
      id: tf-output
      working-directory: ./backend-state
      run: |
        terraform init
        echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config=cloudbuild.yaml \
        --gcs-source-staging-dir=gs://${{ steps.tf-output.outputs.bucket_name }}/tmp \
        --config=cloudbuild.yaml