name: Run Django Migrations

on:
  push:
    branches: [ main ]
    paths:
      - '*/migrations/**'
      - '**/models.py'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: 'Google Auth'
      id: 'auth' 
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        create_credentials_file: true
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Simply trigger Cloud Build without custom substitutions for now
    - name: Run migrations-only build
      run: |
        gcloud builds submit --config=cloudbuild.yaml