name: Run Django Migrations

on:
  push:
    branches: [ main ]
    paths:
      - '*/migrations/**'
      - 'models.py'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: 'Google Auth'
        id: 'auth' 
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
    
      - name: Run migrations-only build
        run: |
          gcloud builds submit \
          --config=cloudbuild.yaml \
          --substitutions=_GS_BUCKET_NAME=roknsound-music-rental-inventory,_REGION=us-central1,_MIGRATIONS_ONLY=1