name: "Terraform Apply Infra"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

permissions:
  id-token: write # Required for AWS OIDC
  contents: read

jobs:
  terraform:
    name: "Apply Infra"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1 # Or your desired version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        # Add -var-file if needed

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
